<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                        => __DIR__ . '/Module.php',
    'Admin\Controller\IndexController' 	  => __DIR__ . '/src/Admin/Controller/IndexController.php',
    'AdminTest\Framework\TestCase'        => __DIR__ . '/tests/Admin/Framework/TestCase.php',
    'AdminTest\SampleTest'                => __DIR__ . '/tests/Admin/SampleTest.php',
);
