<div class="span5">
    <div class="well sidebar-nav">
        <ul class="nav nav-tabs" id="add_form_element">
			<li><a href="#tab_field" data-toggle="tab">Add a Field</a></li>
			<li><a href="#tab_field_prop" data-toggle="tab">Field Prop.</a></li>
			<li><a href="#tab_form_prop" data-toggle="tab">Form Prop.</a></li>
		</ul>
		<div class="tab-content">
		  	<div class="tab-pane active" id="tab_field">
		  		<table class="table table-hover">
		  			<tr>
		  				<td><div class="btn btn-info btn-block" id="single_line_text">Single Line Text</div></td>
		  				<td><div class="btn btn-info btn-block" id="line_number">Number</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block" id="line_paragraph">Paragraph Text</div></td>
		  				<td><div class="btn btn-info btn-block" id="line_checkbox">Checkboxes</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Multiple Choices</div></td>
		  				<td><div class="btn btn-info btn-block">Drop Down</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Name</div></td>
		  				<td><div class="btn btn-info btn-block">Date</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Time</div></td>
		  				<td><div class="btn btn-info btn-block">Phone</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Address</div></td>
		  				<td><div class="btn btn-info btn-block">Web Site</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Price</div></td>
		  				<td><div class="btn btn-info btn-block">Email</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block">Selection Break</div></td>
		  				<td><div class="btn btn-info btn-block">File Upload</div></td>
		  			</tr>
		  		</table>
		  	</div>
		  	<div class="tab-pane" id="tab_field_prop">
		  		<div id="field_properties"></div>
		  	</div>
		  	<div class="tab-pane" id="tab_form_prop">
		  		.vdvdvdvdvdv..
		  	</div>
		</div>
    </div>
</div>