<div class="span3">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <li class="<?= $this->dashboard; ?>"><a href="/admin">Dashboard</a></li>
            <li class="<?= $this->users; ?>"><a href="/admin/users">Users</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class="nav-header">Sidebar</li>
            <li class="ative"><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class="nav-header">Sidebar</li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
            <li class=""><a href="#">Link</a></li>
        </ul>
    </div>
    <!--/.well -->
</div>